<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Laboratorio_15._2_DSIV</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Laboratorio#15-DSIV.ServiceDefaults\Laboratorio#15-DSIV.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
